import fs from "node:fs";
import path from "node:path";

/**
 * Postgres data layer.
 *
 * Two drivers behind one async interface:
 *   - Production (Zale DB): a `pg` connection pool, selected when DATABASE_URL
 *     is set. This is what makes the web tier stateless and horizontally
 *     scalable — every replica talks to the same Postgres.
 *   - Dev / CI / single-node: an embedded PGlite instance (real PostgreSQL
 *     compiled to WASM) persisted under data/pgdata. No external server needed.
 *
 * Both speak the same SQL. A tiny compatibility shim keeps the familiar
 * `db.prepare(sql).get/all/run(...args)` shape from the old SQLite layer, but
 * every call is now async and `?` placeholders are translated to `$n`.
 * Timestamps and durations use DOUBLE PRECISION and identity ids use INTEGER,
 * so both drivers return them as plain JS numbers (no int8-as-string surprises).
 */

const DATA_DIR = path.join(process.cwd(), "data");

type Row = Record<string, unknown>;

interface Driver {
  query(text: string, params: unknown[]): Promise<{ rows: Row[]; affected: number }>;
  exec(text: string): Promise<void>;
}

async function createDriver(): Promise<Driver> {
  const url = process.env.DATABASE_URL;
  if (url) {
    // Real Postgres (Zale DB). int8 -> Number so BIGINT round-trips as a number.
    const pg = await import("pg");
    pg.types.setTypeParser(20, (v: string) => (v === null ? null : Number(v)));
    const pool = new pg.Pool({ connectionString: url, max: 10 });
    return {
      async query(text, params) {
        const r = await pool.query(text, params);
        return { rows: r.rows as Row[], affected: r.rowCount ?? 0 };
      },
      async exec(text) {
        await pool.query(text);
      },
    };
  }
  // Embedded Postgres (PGlite). Persisted so data survives restarts.
  const { PGlite } = await import("@electric-sql/pglite");
  fs.mkdirSync(DATA_DIR, { recursive: true });
  const pglite = await PGlite.create({ dataDir: path.join(DATA_DIR, "pgdata") });
  return {
    async query(text, params) {
      const r = await pglite.query(text, params);
      return { rows: r.rows as Row[], affected: r.affectedRows ?? 0 };
    },
    async exec(text) {
      await pglite.exec(text);
    },
  };
}

const SCHEMA = `
  CREATE TABLE IF NOT EXISTS users (
    id            TEXT PRIMARY KEY,
    email         TEXT NOT NULL UNIQUE,
    name          TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at    DOUBLE PRECISION NOT NULL
  );

  CREATE TABLE IF NOT EXISTS teams (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL,
    slug       TEXT NOT NULL UNIQUE,
    created_at DOUBLE PRECISION NOT NULL
  );

  CREATE TABLE IF NOT EXISTS team_members (
    team_id    TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role       TEXT NOT NULL DEFAULT 'member',
    created_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (team_id, user_id)
  );

  CREATE TABLE IF NOT EXISTS team_invites (
    id         TEXT PRIMARY KEY,
    team_id    TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    email      TEXT NOT NULL,
    role       TEXT NOT NULL DEFAULT 'member',
    created_at DOUBLE PRECISION NOT NULL,
    UNIQUE(team_id, email)
  );

  CREATE TABLE IF NOT EXISTS projects (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name            TEXT NOT NULL,
    slug            TEXT NOT NULL,
    repo_url        TEXT NOT NULL,
    framework       TEXT NOT NULL,
    root_dir        TEXT NOT NULL DEFAULT './',
    build_command   TEXT,
    output_dir      TEXT,
    install_command TEXT,
    node_version    TEXT NOT NULL DEFAULT '22.x',
    region          TEXT NOT NULL DEFAULT 'syd1',
    team_id         TEXT REFERENCES teams(id) ON DELETE CASCADE,
    created_at      DOUBLE PRECISION NOT NULL,
    UNIQUE(user_id, slug)
  );

  CREATE TABLE IF NOT EXISTS deployments (
    id           TEXT PRIMARY KEY,
    project_id   TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    url_slug     TEXT NOT NULL UNIQUE,
    status       TEXT NOT NULL DEFAULT 'QUEUED',
    environment  TEXT NOT NULL DEFAULT 'production',
    branch       TEXT NOT NULL DEFAULT 'main',
    commit_sha   TEXT NOT NULL,
    commit_msg   TEXT NOT NULL,
    created_at   DOUBLE PRECISION NOT NULL,
    finished_at  DOUBLE PRECISION,
    duration_ms  DOUBLE PRECISION,
    is_current   INTEGER NOT NULL DEFAULT 0,
    next_step    INTEGER NOT NULL DEFAULT 0,
    next_run_at  DOUBLE PRECISION
  );

  CREATE TABLE IF NOT EXISTS deployment_logs (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deployment_id TEXT NOT NULL REFERENCES deployments(id) ON DELETE CASCADE,
    ts            DOUBLE PRECISION NOT NULL,
    level         TEXT NOT NULL DEFAULT 'info',
    message       TEXT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_logs_deployment ON deployment_logs(deployment_id, id);

  CREATE TABLE IF NOT EXISTS env_vars (
    id          TEXT PRIMARY KEY,
    project_id  TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    targets     TEXT NOT NULL DEFAULT 'production,preview,development',
    created_at  DOUBLE PRECISION NOT NULL
  );

  CREATE TABLE IF NOT EXISTS domains (
    id                 TEXT PRIMARY KEY,
    project_id         TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name               TEXT NOT NULL UNIQUE,
    verified           INTEGER NOT NULL DEFAULT 0,
    is_primary         INTEGER NOT NULL DEFAULT 0,
    verification_token TEXT NOT NULL DEFAULT '',
    created_at         DOUBLE PRECISION NOT NULL
  );

  CREATE TABLE IF NOT EXISTS sessions (
    token      TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL
  );

  CREATE TABLE IF NOT EXISTS api_tokens (
    id         TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    last_used  DOUBLE PRECISION,
    created_at DOUBLE PRECISION NOT NULL
  );

  CREATE TABLE IF NOT EXISTS deploy_hooks (
    id         TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    token      TEXT NOT NULL UNIQUE,
    branch     TEXT NOT NULL DEFAULT 'main',
    created_at DOUBLE PRECISION NOT NULL
  );

  CREATE TABLE IF NOT EXISTS user_plans (
    user_id    TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    plan       TEXT NOT NULL DEFAULT 'hobby',
    updated_at DOUBLE PRECISION NOT NULL
  );

  CREATE TABLE IF NOT EXISTS activity (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    actor      TEXT NOT NULL,
    type       TEXT NOT NULL,
    message    TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_activity_project ON activity(project_id, id DESC);

  -- Zale DB: managed databases attached to a project. The primary branch is
  -- created with the database; preview deployments each fork their own branch.
  CREATE TABLE IF NOT EXISTS databases (
    id                    TEXT PRIMARY KEY,
    project_id            TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name                  TEXT NOT NULL,
    region                TEXT NOT NULL DEFAULT 'syd1',
    status                TEXT NOT NULL DEFAULT 'available',
    zdb_project_id        TEXT,
    zdb_default_branch_id TEXT,
    created_at            DOUBLE PRECISION NOT NULL,
    UNIQUE(project_id, name)
  );

  CREATE TABLE IF NOT EXISTS db_branches (
    id            TEXT PRIMARY KEY,
    database_id   TEXT NOT NULL REFERENCES databases(id) ON DELETE CASCADE,
    name          TEXT NOT NULL,
    kind          TEXT NOT NULL DEFAULT 'preview',
    parent_branch TEXT,
    deployment_id TEXT REFERENCES deployments(id) ON DELETE CASCADE,
    status        TEXT NOT NULL DEFAULT 'available',
    zdb_branch_id TEXT,
    created_at    DOUBLE PRECISION NOT NULL,
    UNIQUE(database_id, name)
  );
  CREATE INDEX IF NOT EXISTS idx_branches_database ON db_branches(database_id, created_at);
  CREATE INDEX IF NOT EXISTS idx_branches_deployment ON db_branches(deployment_id) WHERE deployment_id IS NOT NULL;

  CREATE TABLE IF NOT EXISTS db_credentials (
    id           TEXT PRIMARY KEY,
    branch_id    TEXT NOT NULL REFERENCES db_branches(id) ON DELETE CASCADE,
    role         TEXT NOT NULL DEFAULT 'owner',
    username     TEXT NOT NULL,
    password_enc TEXT NOT NULL,
    created_at   DOUBLE PRECISION NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_credentials_branch ON db_credentials(branch_id);

  -- Tamper-evident audit log. Each row's hash chains the previous row's hash,
  -- so any edit, deletion or reordering breaks the chain and is detectable.
  CREATE TABLE IF NOT EXISTS audit_log (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts        DOUBLE PRECISION NOT NULL,
    actor_id  TEXT,
    actor     TEXT NOT NULL,
    action    TEXT NOT NULL,
    target    TEXT,
    trace_id  TEXT,
    metadata  TEXT,
    prev_hash TEXT NOT NULL,
    hash      TEXT NOT NULL
  );
  CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_log(actor_id, id DESC);

  -- Multi-region: per-region health, and the regional rollout of each deployment.
  CREATE TABLE IF NOT EXISTS region_health (
    region     TEXT PRIMARY KEY,
    status     TEXT NOT NULL DEFAULT 'operational',
    latency_ms INTEGER NOT NULL DEFAULT 20,
    updated_at DOUBLE PRECISION NOT NULL
  );

  CREATE TABLE IF NOT EXISTS deployment_regions (
    deployment_id TEXT NOT NULL REFERENCES deployments(id) ON DELETE CASCADE,
    region        TEXT NOT NULL,
    role          TEXT NOT NULL DEFAULT 'edge',
    status        TEXT NOT NULL DEFAULT 'pending',
    PRIMARY KEY (deployment_id, region)
  );
  CREATE INDEX IF NOT EXISTS idx_depregions_region ON deployment_regions(region, status);

  -- Migrations for databases created before a column existed (idempotent).
  ALTER TABLE deployments ADD COLUMN IF NOT EXISTS next_step INTEGER NOT NULL DEFAULT 0;
  ALTER TABLE deployments ADD COLUMN IF NOT EXISTS next_run_at DOUBLE PRECISION;
  CREATE INDEX IF NOT EXISTS idx_deployments_due ON deployments(next_run_at) WHERE next_run_at IS NOT NULL;
  ALTER TABLE domains ADD COLUMN IF NOT EXISTS verification_token TEXT NOT NULL DEFAULT '';
  -- Zale DB control-plane references (null for simulated/dev databases).
  ALTER TABLE databases ADD COLUMN IF NOT EXISTS zdb_project_id TEXT;
  ALTER TABLE databases ADD COLUMN IF NOT EXISTS zdb_default_branch_id TEXT;
  ALTER TABLE db_branches ADD COLUMN IF NOT EXISTS zdb_branch_id TEXT;
`;

// Cache on globalThis so Next.js dev HMR doesn't open duplicate handles.
const globalForDb = globalThis as unknown as { __zaleDbReady?: Promise<Driver> };

async function bootstrap(): Promise<Driver> {
  const driver = await createDriver();
  await driver.exec(SCHEMA);
  return driver;
}

/**
 * Shared, lazily-initialized driver. If bootstrap rejects (e.g. Postgres briefly
 * unreachable at boot) the cached promise is cleared so the next query retries,
 * rather than poisoning the process with a permanently-rejected promise.
 */
function ready(): Promise<Driver> {
  if (!globalForDb.__zaleDbReady) {
    const p = bootstrap();
    globalForDb.__zaleDbReady = p;
    p.catch(() => {
      if (globalForDb.__zaleDbReady === p) globalForDb.__zaleDbReady = undefined;
    });
  }
  return globalForDb.__zaleDbReady;
}

/** Translate `?` positional placeholders to Postgres `$1, $2, …`. */
function toPg(sql: string): string {
  let i = 0;
  return sql.replace(/\?/g, () => `$${++i}`);
}

type Prepared = {
  get<T = Row>(...params: unknown[]): Promise<T | undefined>;
  all<T = Row>(...params: unknown[]): Promise<T[]>;
  run(...params: unknown[]): Promise<{ changes: number }>;
};

/**
 * Compatibility shim mirroring better-sqlite3's `prepare().get/all/run`, but
 * async and Postgres-backed. SQL keeps `?` placeholders; the shim converts
 * them and awaits the shared driver (which finishes schema init first).
 */
export const db = {
  prepare(sql: string): Prepared {
    const text = toPg(sql);
    return {
      async get<T = Row>(...params: unknown[]): Promise<T | undefined> {
        const d = await ready();
        const { rows } = await d.query(text, params);
        return rows[0] as T | undefined;
      },
      async all<T = Row>(...params: unknown[]): Promise<T[]> {
        const d = await ready();
        const { rows } = await d.query(text, params);
        return rows as T[];
      },
      async run(...params: unknown[]): Promise<{ changes: number }> {
        const d = await ready();
        const { affected } = await d.query(text, params);
        return { changes: affected };
      },
    };
  },
  /** Await schema readiness explicitly (used by health checks). */
  async ready(): Promise<void> {
    await ready();
  },
};
